name: Swagger Autogen

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Read-only is enough since we no longer push commits
permissions:
  contents: read

jobs:
  docs:
    name: Generate Swagger Docs
    runs-on: ubuntu-latest
    env:
      SWAG_VERSION: v1.16.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install swag CLI
        run: |
          go install github.com/swaggo/swag/cmd/swag@${SWAG_VERSION}
          echo "$HOME/go/bin" >> $GITHUB_PATH
          swag -v

      - name: Generate Swagger docs
        run: |
          swag init -g main.go -o docs

      - name: Fail if docs changed
        shell: bash
        run: |
          # Show a concise summary of changes (includes untracked files)
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::group::Changed files"
            git status --porcelain
            echo "::endgroup::"

            echo "::group::Diff"
            # --no-ext-diff to avoid external diff tools; may be noisy if many files changed
            git --no-pager diff --no-ext-diff || true
            echo "::endgroup::"

            echo "::error::Swagger docs are out of date. Run 'swag init' locally and commit the results."
            exit 1
          fi
